// pages/colleges.tsx
import React, { useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";

type College = {
  id: string;
  name: string;
  city?: string;
  short: string;
  img: string;
  url?: string;
  type?: "Government" | "Private" | "Deemed" | "Other";
  nirf?: number | string;
  fees?: string;
  closingRank?: string | number;
  hostel?: boolean;
  premium?: boolean;
};

const colleges: College[] = [
  // existing ones (kept for continuity)
  {
    id: "smsr",
    name: "Sharda School of Medical Science and Research",
    city: "Greater Noida, Uttar Pradesh",
    short:
      "Established in 2009 under Sharda University. Approved by MCI, strong clinical exposure and research focus.",
    img: "/images/college1.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹9,00,000 / year",
    closingRank: "45,000 (State)",
    hostel: true,
    premium: true,
  },
  {
    id: "hims",
    name: "Hind Institute Of Medical Sciences",
    city: "Sitapur / Lucknow, Uttar Pradesh",
    short:
      "Top-tier specialized medical education with modern clinical facilities and major surgical departments.",
    img: "/images/college2.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹7,50,000 / year",
    closingRank: "50,000 (State)",
    hostel: true,
  },
  {
    id: "rama",
    name: "Rama Medical College Hospital & Research Centre",
    city: "Hapur, Uttar Pradesh",
    short:
      "Prestigious institution offering MBBS & postgraduate degrees across many specialties with excellent campus.",
    img: "/images/college3.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹8,00,000 / year",
    closingRank: "48,000 (State)",
    hostel: true,
    premium: true,
  },
  {
    id: "subharti",
    name: "Subharti Medical College, Meerut",
    city: "Meerut, Uttar Pradesh",
    short:
      "One of Northern India's reputed medical colleges with updated AV teaching aids and campus facilities.",
    img: "/images/college4.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹6,50,000 / year",
    closingRank: "52,000 (State)",
    hostel: true,
  },
  {
    id: "hamdard",
    name: "Hamdard Institute of Medical Sciences & Research",
    city: "New Delhi",
    short:
      "Well-known institute with attached teaching hospital and multiple specialty departments for clinical exposure.",
    img: "/images/college5.jpg",
    url: "#",
    type: "Deemed",
    nirf: "—",
    fees: "₹10,00,000 / year",
    closingRank: "34,000 (AIQ)",
    hostel: true,
  },
  {
    id: "amrita",
    name: "Amrita School of Medicine, Faridabad",
    city: "Faridabad, Haryana",
    short:
      "Modern campus with integrated research and student-centered learning environment.",
    img: "/images/college6.jpg",
    url: "#",
    type: "Deemed",
    nirf: 45,
    fees: "₹11,00,000 / year",
    closingRank: "30,000 (AIQ)",
    hostel: true,
  },

  
 
  {
    id: "nims-jaipur",
    name: "National Institute of Medical Sciences & Research (NIMS)",
    city: "Jaipur, Rajasthan",
    short:
      "Large teaching hospital and research-focused institute with varied postgraduate opportunities and clinical exposure.",
    img: "/images/college10.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹8,50,000 / year",
    closingRank: "40,000 (AIQ)",
    hostel: true,
  },
  {
    id: "himalayan-institute",
    name: "Himalayan Institute of Medical Sciences",
    city: "Dehradun, Uttarakhand",
    short:
      "Mountain-region medical college with an emphasis on community medicine and emergency care training.",
    img: "/images/college11.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹6,50,000 / year",
    closingRank: "65,000 (State)",
    hostel: true,
  },
  {
    id: "guru-ram-rai",
    name: "Shri Guru Ram Rai Institute of Medical & Health Sciences",
    city: "Dehradun, Uttarakhand",
    short:
      "Well-regarded regional institute with multi-specialty hospital attached and significant clinical case load.",
    img: "/images/college12.jpg",
    url: "#",
    type: "Deemed",
    nirf: "—",
    fees: "₹9,00,000 / year",
    closingRank: "38,000 (AIQ)",
    hostel: true,
    premium: true,
  },
  {
    id: "sri-aurobindo",
    name: "Sri Aurobindo Institute of Medical Sciences",
    city: "Indore, Madhya Pradesh",
    short:
      "Established medical college with strong teaching hospital and active research/continuing medical education programs.",
    img: "/images/college13.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹7,00,000 / year",
    closingRank: "55,000 (State)",
    hostel: true,
  },
  {
    id: "chirayu",
    name: "Chirayu Medical College & Hospital",
    city: "Bhopal, Madhya Pradesh",
    short:
      "Major referral hospital in the region — good variety of clinical material and hands-on training opportunities.",
    img: "/images/college14.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹6,50,000 / year",
    closingRank: "58,000 (State)",
    hostel: true,
  },
  {
    id: "dy-patil",
    name: "DY Patil Medical College, Pune",
    city: "Pune, Maharashtra",
    short:
      "Reputed private medical college with updated infrastructure, strong faculty and good placement/support systems.",
    img: "/images/college15.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹10,00,000 / year",
    closingRank: "35,000 (AIQ)",
    hostel: true,
    premium: true,
  },
  {
    id: "symbiosis",
    name: "Symbiosis Medical College for Women, Pune",
    city: "Pune, Maharashtra",
    short:
      "Focused women's medical college with modern labs and strong campus safety/support — growing academic profile.",
    img: "/images/college16.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹8,50,000 / year",
    closingRank: "45,000 (State)",
    hostel: true,
  },
  
  {
    id: "vydehi",
    name: "Vydehi Institute of Medical Sciences & Research Centre",
    city: "Bengaluru, Karnataka",
    short:
      "Large referral hospital attached to the college, offering broad clinical exposure across specialties.",
    img: "/images/college18.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹9,50,000 / year",
    closingRank: "33,000 (AIQ)",
    hostel: true,
  },
   {
    id: "srms-bareilly",
    name: "Sri Rama Murti Smarak Institute of Medical Sciences",
    city: "Bareilly, Uttar Pradesh",
    short:
      "Established in 2005, SRMS IMS Bareilly is a reputed private medical college with strong clinical exposure and modern hospital facilities.",
    img: "/images/college19.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹19,78,214 / year",
    hostel: true,
  },
  {
    id: "sharda-smsr",
    name: "School of Medical Sciences (Sharda University)",
    city: "Greater Noida, Uttar Pradesh",
    short:
      "Founded in 2009 under Sharda University, known for modern infrastructure, research focus and strong academic environment.",
    img: "/images/college20.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹15,23,183 / year",
    hostel: true,
    premium: true,
  },
  {
    id: "subharti-meerut",
    name: "Subharti Medical College",
    city: "Meerut, Uttar Pradesh",
    short:
      "Established in 1996, Subharti Medical College offers comprehensive medical education with a large teaching hospital.",
    img: "/images/college21.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹14,22,160 / year",
    hostel: true,
  },
  {
    id: "hims-barabanki",
    name: "Hind Institute of Medical Sciences",
    city: "Barabanki, Uttar Pradesh",
    short:
      "Private medical college established in 2009, providing quality MBBS education with good patient flow.",
    img: "/images/college22.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹16,85,681 / year",
    hostel: true,
  },
  {
    id: "mmc-muzaffarnagar",
    name: "Muzaffarnagar Medical College",
    city: "Muzaffarnagar, Uttar Pradesh",
    short:
      "Established in 2006, MMC Muzaffarnagar is known for its large campus and extensive clinical exposure.",
    img: "/images/college23.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹16,72,660 / year",
    hostel: true,
  },
  {
    id: "sims-hapur",
    name: "Saraswathi Institute of Medical Sciences",
    city: "Hapur, Uttar Pradesh",
    short:
      "Founded in 2008, SIMS Hapur offers affordable private MBBS education with attached teaching hospital.",
    img: "/images/college24.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹11,81,671 / year",
    hostel: true,
  },
  {
    id: "rmc-bareilly",
    name: "Rohilkhand Medical College & Hospital",
    city: "Bareilly, Uttar Pradesh",
    short:
      "Established in 2006, Rohilkhand Medical College is a well-known private institution with strong academics.",
    img: "/images/college25.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹18,72,361 / year",
    hostel: true,
  },
  {
    id: "hims-varanasi",
    name: "Heritage Institute of Medical Sciences",
    city: "Varanasi, Uttar Pradesh",
    short:
      "Founded in 2015, Heritage IMS Varanasi provides modern medical education with expanding hospital facilities.",
    img: "/images/college26.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹13,21,492 / year",
    hostel: true,
  },
  {
    id: "rama-kanpur",
    name: "Rama Medical College Hospital & Research Centre",
    city: "Kanpur, Uttar Pradesh",
    short:
      "Established in 2008, Rama Medical College Kanpur focuses on quality education and clinical training.",
    img: "/images/college27.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹15,19,895 / year",
    hostel: true,
  },
  {
    id: "hims-sitapur",
    name: "Hind Institute of Medical Sciences",
    city: "Sitapur, Uttar Pradesh",
    short:
      "Private medical college established in 2015, offering MBBS education with modern facilities and teaching hospital.",
    img: "/images/college28.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹12,92,675 / year",
    hostel: true,
  },
  {
    id: "mims-lucknow",
    name: "Mayo Institute of Medical Sciences",
    city: "Lucknow, Uttar Pradesh",
    short:
      "Established in 2012, Mayo Institute of Medical Sciences provides quality medical education with good clinical exposure.",
    img: "/images/college29.jpg",
    url: "#",
    type: "Private",
    nirf: "—",
    fees: "₹11,21,162 / year",
    hostel: true,
  },
{
  id: "kd-mathura",
  name: "K.D. Medical College Hospital & Research Center",
  city: "Mathura, Uttar Pradesh",
  short: "Established in 2015, KD Medical College offers MBBS education with modern infrastructure and hospital facilities.",
  img: "/images/college30.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,28,240 / year",
  hostel: true,
},
{
  id: "rajshree-bareilly",
  name: "Rajshree Medical Research Institute",
  city: "Bareilly, Uttar Pradesh",
  short: "Founded in 2014, known for strong academics and good clinical exposure.",
  img: "/images/college31.jpg",
  url: "#",
  type: "Private",
  fees: "₹17,68,904 / year",
  hostel: true,
},
{
  id: "rama-hapur-2011",
  name: "Rama Medical College Hospital & Research Centre",
  city: "Hapur, Uttar Pradesh",
  short: "Established in 2011, focuses on quality education and patient-based learning.",
  img: "/images/college32.jpg",
  url: "#",
  type: "Private",
  fees: "₹13,09,968 / year",
  hostel: true,
},
{
  id: "prasad-lucknow",
  name: "Prasad Institute of Medical Sciences",
  city: "Lucknow, Uttar Pradesh",
  short: "Established in 2016, provides balanced academics and hospital exposure.",
  img: "/images/college33.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,03,932 / year",
  hostel: true,
},
{
  id: "ts-mishra-lucknow",
  name: "T.S. Mishra Medical College & Hospital",
  city: "Lucknow, Uttar Pradesh",
  short: "Founded in 2016, known for advanced infrastructure and large hospital setup.",
  img: "/images/college34.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,70,847 / year",
  hostel: true,
  premium: true,
},
{
  id: "noida-international",
  name: "Noida International Institute of Medical Sciences",
  city: "Greater Noida, Uttar Pradesh",
  short: "Established in 2020, offers modern medical education with developing multi-specialty hospital.",
  img: "/images/college35.jpg",
  url: "#",
  type: "Private",
  fees: "₹17,16,784 / year",
  hostel: true,
},
{
  id: "gs-hapur",
  name: "G.S. Medical College & Hospital",
  city: "Hapur, Uttar Pradesh",
  short: "Founded in 2017, provides quality MBBS education with clinical exposure.",
  img: "/images/college36.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,42,654 / year",
  hostel: true,
},
{
  id: "saraswati-unnao",
  name: "Saraswati Medical College",
  city: "Unnao, Uttar Pradesh",
  short: "Established in 2016, known for affordable private MBBS education in UP.",
  img: "/images/college37.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,59,610 / year",
  hostel: true,
},
{
  id: "uims-prayagraj",
  name: "United Institute of Medical Sciences",
  city: "Prayagraj, Uttar Pradesh",
  short: "Established in 2020, offers modern teaching facilities with hospital exposure.",
  img: "/images/college38.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,90,401 / year",
  hostel: true,
},
{
  id: "ncr-meerut",
  name: "NCR Institute of Medical Sciences",
  city: "Meerut, Uttar Pradesh",
  short: "Founded in 2018, provides MBBS education with improving clinical facilities.",
  img: "/images/college39.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,19,917 / year",
  hostel: true,
},
{
  id: "krishna-mohan-mathura",
  name: "Krishna Mohan Medical College & Hospital",
  city: "Mathura, Uttar Pradesh",
  short: "Established in 2016, focuses on quality teaching and clinical exposure.",
  img: "/images/college40.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,73,856 / year",
  hostel: true,
},
{
  id: "varun-arjun-shahjahanpur",
  name: "Varun Arjun Medical College",
  city: "Shahjahanpur, Uttar Pradesh",
  short: "Founded in 2016, offers MBBS education with modern infrastructure.",
  img: "/images/college41.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,52,000 / year",
  hostel: true,
},
{
  id: "venkateshwara-amroha",
  name: "Venkateshwara Institute of Medical Sciences",
  city: "Amroha, Uttar Pradesh",
  short: "Established in 2016, known for student-friendly campus and hospital exposure.",
  img: "/images/college42.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,10,508 / year",
  hostel: true,
},
{
  id: "naraina-kanpur",
  name: "Naraina Medical College & Hospital",
  city: "Kanpur, Uttar Pradesh",
  short: "Founded in 2021, offers modern MBBS education with developing hospital facilities.",
  img: "/images/college43.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,14,683 / year",
  hostel: true,
},
{
  id: "sks-mathura",
  name: "SKS Medical College",
  city: "Mathura, Uttar Pradesh",
  short: "Established in 2017, provides MBBS education with clinical exposure.",
  img: "/images/college44.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,14,683 / year",
  hostel: true,
},
{
  id: "kmc-ppp-maharajganj",
  name: "KMC Medical College & Hospital (PPP)",
  city: "Maharajganj, Uttar Pradesh",
  short: "Established in 2024 under PPP model, providing modern MBBS education with government-supported hospital facilities.",
  img: "/images/college45.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,14,159 / year",
  hostel: true,
},
{
  id: "ajay-sangaal-shamli",
  name: "Ajay Sangaal Institute of Medical Sciences (PPP)",
  city: "Shamli, Uttar Pradesh",
  short: "Established in 2024 under PPP model, focused on quality medical education and clinical exposure.",
  img: "/images/college46.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,14,159 / year",
  hostel: true,
},
{
  id: "gorakshnath-ppp-gorakhpur",
  name: "Shri Gorakshnath Medical College (PPP)",
  city: "Gorakhpur, Uttar Pradesh",
  short: "Founded in 2024 under PPP model, associated with a large government hospital for strong clinical training.",
  img: "/images/college47.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,14,159 / year",
  hostel: true,
},
{
  id: "siddhi-vinayak-ppp-sambhal",
  name: "Shri Siddhi Vinayak Medical College (PPP)",
  city: "Sambhal, Uttar Pradesh",
  short: "Established in 2024 under PPP framework, offering MBBS education with developing infrastructure.",
  img: "/images/college48.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,14,159 / year",
  hostel: true,
},
{
  id: "bs-kushwah-kanpur",
  name: "Dr. B.S. Kushwah Institute of Medical Sciences",
  city: "Kanpur, Uttar Pradesh",
  short: "Founded in 2024, providing modern MBBS education with new-age facilities and hospital exposure.",
  img: "/images/college49.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,14,159 / year",
  hostel: true,
},
{
  id: "tmu-moradabad",
  name: "Teerthanker Mahaveer Medical College & Research Centre",
  city: "Moradabad, Uttar Pradesh",
  short: "Established in 2008, part of TMU with strong academics, hospital infrastructure and clinical exposure.",
  img: "/images/college50.jpg",
  url: "#",
  type: "Private",
  fees: "₹16,20,000 / year",
  hostel: true,
},
{
  id: "fh-agra-minority",
  name: "F.H. Medical College & Hospital (Muslim Minority)",
  city: "Agra, Uttar Pradesh",
  short: "Established in 2014, minority institution offering MBBS education with good clinical exposure.",
  img: "/images/college51.jpg",
  url: "#",
  type: "Private",
  fees: "₹17,95,000 / year",
  hostel: true,
},
{
  id: "era-lucknow-minority",
  name: "Era Medical College (Muslim Minority)",
  city: "Lucknow, Uttar Pradesh",
  short: "Founded in 1997, one of the oldest minority medical colleges in UP with strong academics.",
  img: "/images/college52.jpg",
  url: "#",
  type: "Private",
  fees: "₹16,60,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "career-lucknow-minority",
  name: "Career Institute of Medical Sciences (Minority)",
  city: "Lucknow, Uttar Pradesh",
  short: "Established in 2011, minority medical college with balanced academics and hospital training.",
  img: "/images/college53.jpg",
  url: "#",
  type: "Private",
  fees: "₹16,50,000 / year",
  hostel: true,
},
{
  id: "integral-lucknow-minority",
  name: "Integral Institute of Medical Sciences & Research (Minority)",
  city: "Lucknow, Uttar Pradesh",
  short: "Founded in 2013 under Integral University, known for large campus and modern medical facilities.",
  img: "/images/college54.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "santosh-ghaziabad-deemed",
  name: "Santosh Medical College & Hospital",
  city: "Ghaziabad, Uttar Pradesh",
  short: "Established in 1996, deemed university medical college with long-standing reputation and infrastructure.",
  img: "/images/college55.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹24,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "aims-udaipur",
  name: "American Institute of Medical Sciences",
  city: "Udaipur, Rajasthan",
  short: "Established in 2016, private medical college with modern infrastructure and attached teaching hospital.",
  img: "/images/college56.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "ananta-rajsamand",
  name: "Ananta Institute of Medical Sciences",
  city: "Rajsamand, Rajasthan",
  short: "Founded in 2016, known for student-friendly campus and growing clinical exposure.",
  img: "/images/college57.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "geetanjali-udaipur",
  name: "Geetanjali Medical College & Hospital",
  city: "Udaipur, Rajasthan",
  short: "Established in 2008, one of the reputed medical colleges in Rajasthan with strong academics.",
  img: "/images/college58.jpg",
  url: "#",
  type: "Private",
  fees: "₹23,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "jnu-jaipur",
  name: "JNU Institute for Medical Sciences",
  city: "Jaipur, Rajasthan",
  short: "Founded in 2016 under Jaipur National University with modern teaching facilities.",
  img: "/images/college59.jpg",
  url: "#",
  type: "Private",
  fees: "₹23,00,000 / year",
  hostel: true,
},
{
  id: "mgmc-jaipur",
  name: "Mahatma Gandhi Medical College & Hospital",
  city: "Jaipur, Rajasthan",
  short: "Established in 2001, well-known medical college with strong hospital infrastructure and academics.",
  img: "/images/college9.jpg",
  url: "#",
  type: "Private",
  fees: "₹19,50,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "nims-jaipur-2",
  name: "National Institute of Medical Sciences (NIMS)",
  city: "Jaipur, Rajasthan",
  short: "Founded in 2004, large medical university with extensive clinical exposure and research focus.",
  img: "/images/college61.jpg",
  url: "#",
  type: "Private",
  fees: "₹24,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "pacific-ims-udaipur",
  name: "Pacific Institute of Medical Sciences",
  city: "Udaipur, Rajasthan",
  short: "Established in 2015, offers MBBS education with developing multi-specialty hospital.",
  img: "/images/college62.jpg",
  url: "#",
  type: "Private",
  fees: "₹25,00,000 / year",
  hostel: true,
},
{
  id: "pacific-mch-udaipur",
  name: "Pacific Medical College & Hospital",
  city: "Udaipur, Rajasthan",
  short: "Founded in 2014, known for its clinical exposure and campus facilities.",
  img: "/images/college63.jpg",
  url: "#",
  type: "Private",
  fees: "₹25,00,000 / year",
  hostel: true,
},
{
  id: "tantia-sriganganagar",
  name: "Dr. S.S. Tantia Medical College Hospital & Research Centre",
  city: "Sri Ganganagar, Rajasthan",
  short: "Established in 2021, provides modern medical education with attached teaching hospital.",
  img: "/images/college64.jpg",
  url: "#",
  type: "Private",
  fees: "₹22,25,000 / year",
  hostel: true,
},
{
  id: "sudha-kota",
  name: "Sudha Medical College & Hospital",
  city: "Kota, Rajasthan",
  short: "Founded in 2024, new medical college with modern infrastructure and clinical facilities.",
  img: "/images/college65.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "vyas-jodhpur",
  name: "Vyas Medical College & Hospital",
  city: "Jodhpur, Rajasthan",
  short: "Established in 2024, offers MBBS education with modern campus and hospital facilities.",
  img: "/images/college66.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "jiet-jodhpur",
  name: "JIET Medical College & Hospital",
  city: "Jodhpur, Rajasthan",
  short: "Established in 2024, JIET Medical College offers modern MBBS education with developing hospital facilities.",
  img: "/images/college67.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "balvir-singh-tomar-jaipur",
  name: "Balvir Singh Tomar Institute of Medical Sciences",
  city: "Jaipur, Rajasthan",
  short: "Established in 2026, new private medical college with modern infrastructure and teaching facilities.",
  img: "/images/college68.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "geetanjali-ims-jaipur",
  name: "Geetanjali Institute of Medical Sciences",
  city: "Jaipur, Rajasthan",
  short: "Founded in 2026, offers MBBS education with contemporary campus and hospital exposure.",
  img: "/images/college69.jpg",
  url: "#",
  type: "Private",
  fees: "₹18,90,000 / year",
  hostel: true,
},
{
  id: "katihar-medical-college",
  name: "Katihar Medical College & Hospital",
  city: "Katihar, Bihar",
  short: "Established in 1987, one of the oldest private medical colleges in Bihar with strong clinical exposure.",
  img: "/images/college70.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,05,000 / year",
  hostel: true,
},
{
  id: "narayan-sasaram",
  name: "Narayan Medical College & Hospital",
  city: "Sasaram, Bihar",
  short: "Founded in 2008, provides MBBS education with a large teaching hospital and clinical exposure.",
  img: "/images/college7.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,25,000 / year",
  hostel: true,
},
{
  id: "mata-gujri-kishanganj",
  name: "Mata Gujri Memorial Medical College",
  city: "Kishanganj, Bihar",
  short: "Established in 1990, known for affordable medical education and good patient flow.",
  img: "/images/college8.jpg",
  url: "#",
  type: "Private",
  fees: "₹9,63,000 / year",
  hostel: true,
},
{
  id: "lord-buddha-saharsa",
  name: "Lord Buddha Medical College & Hospital",
  city: "Saharsa, Bihar",
  short: "Founded in 2019, modern private medical college with developing hospital facilities.",
  img: "/images/college73.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,00,000 / year",
  hostel: true,
},
{
  id: "madhubani-medical-college",
  name: "Madhubani Medical College & Hospital",
  city: "Madhubani, Bihar",
  short: "Established in 2019, offers MBBS education with modern infrastructure.",
  img: "/images/college74.jpg",
  url: "#",
  type: "Private",
  fees: "₹14,00,000 / year",
  hostel: true,
},
{
  id: "shri-narayan-saharsa",
  name: "Shri Narayan Medical College & Hospital",
  city: "Saharsa, Bihar",
  short: "Founded in 2021, provides MBBS education with improving clinical exposure.",
  img: "/images/college75.jpg",
  url: "#",
  type: "Private",
  fees: "₹12,05,000 / year",
  hostel: true,
},
{
  id: "rdjm-muzaffarpur",
  name: "RDJM Medical College & Hospital",
  city: "Muzaffarpur, Bihar",
  short: "Established in 2021, known for student-friendly campus and hospital exposure.",
  img: "/images/college76.jpg",
  url: "#",
  type: "Private",
  fees: "₹11,90,000 / year",
  hostel: true,
},
{
  id: "netaji-subhas-patna",
  name: "Netaji Subhas Medical College & Hospital",
  city: "Patna, Bihar",
  short: "Founded in 2020, reputed private medical college with strong academics.",
  img: "/images/college77.jpg",
  url: "#",
  type: "Private",
  fees: "₹16,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "himalaya-patna",
  name: "Himalaya Medical College & Hospital",
  city: "Patna, Bihar",
  short: "Established in 2024, new medical college with modern infrastructure and facilities.",
  img: "/images/college78.jpg",
  url: "#",
  type: "Private",
  fees: "₹16,50,000 / year",
  hostel: true,
},
{
  id: "mahabodhi-gaya",
  name: "Mahabodhi Medical College & Hospital",
  city: "Gaya, Bihar",
  short: "Founded in 2026, developing medical college with modern campus and hospital setup.",
  img: "/images/college79.jpg",
  url: "#",
  type: "Private",
  fees: "₹17,25,000 / year",
  hostel: true,
},
{
  id: "shyamlal-chandrashekhar-khagaria",
  name: "Shyamlal Chandrashekhar Medical College & Hospital",
  city: "Khagaria, Bihar",
  short: "Established in 2026, offers MBBS education with modern facilities and teaching hospital.",
  img: "/images/college80.jpg",
  url: "#",
  type: "Private",
  fees: "₹16,50,000 / year",
  hostel: true,
},
{
  id: "aiims-patna",
  name: "All India Institute of Medical Sciences (AIIMS)",
  city: "Patna, Bihar",
  short: "Premier government medical institute under AIIMS with advanced healthcare, academics and research facilities.",
  img: "/images/college81.jpg",
  url: "#",
  type: "Government",
  hostel: true,
  premium: true,
},
{
  id: "pmch-patna",
  name: "Patna Medical College & Hospital",
  city: "Patna, Bihar",
  short: "One of the oldest medical colleges in India, known for high patient load and strong clinical exposure.",
  img: "/images/college82.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "anmmc-gaya",
  name: "Anugrah Narayan Magadh Medical College & Hospital",
  city: "Gaya, Bihar",
  short: "Reputed government medical college providing quality MBBS education and clinical training.",
  img: "/images/college83.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "nmch-patna",
  name: "Nalanda Medical College & Hospital",
  city: "Patna, Bihar",
  short: "Major government medical college with strong academics and extensive hospital facilities.",
  img: "/images/college84.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "skmch-muzaffarpur",
  name: "Sri Krishna Medical College & Hospital",
  city: "Muzaffarpur, Bihar",
  short: "Well-known government medical college with large patient inflow and clinical exposure.",
  img: "/images/college85.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "jnmch-bhagalpur",
  name: "Jawaharlal Nehru Medical College & Hospital",
  city: "Bhagalpur, Bihar",
  short: "Established government medical college offering MBBS education with comprehensive clinical training.",
  img: "/images/college86.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "igims-patna",
  name: "Indira Gandhi Institute of Medical Sciences (IGIMS)",
  city: "Patna, Bihar",
  short: "Autonomous government institute with super-speciality focus and modern medical infrastructure.",
  img: "/images/college87.jpg",
  url: "#",
  type: "Government",
  hostel: true,
  premium: true,
},
{
  id: "vims-pawapuri",
  name: "Vardhman Institute of Medical Sciences",
  city: "Pawapuri, Nalanda, Bihar",
  short: "Government medical college serving Nalanda region with growing academic and hospital facilities.",
  img: "/images/college88.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "gmc-bettiah",
  name: "Government Medical College",
  city: "Bettiah, Bihar",
  short: "New government medical college aimed at improving healthcare access in West Champaran region.",
  img: "/images/college89.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "gmc-purnea",
  name: "Government Medical College",
  city: "Purnea, Bihar",
  short: "Government medical college established to strengthen medical education and healthcare in Seemanchal region.",
  img: "/images/college90.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "jk-t-medical-madhepura",
  name: "Jannayak Karpoori Thakur Medical College & Hospital",
  city: "Madhepura, Bihar",
  short: "Government medical college named after Karpoori Thakur, offering MBBS education with regional healthcare focus.",
  img: "/images/college91.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "sheikhpura-medical-college",
  name: "Sheikhpura Medical College & Hospital",
  city: "Sheikhpura, Bihar",
  short: "Government medical college with developing infrastructure and teaching hospital.",
  img: "/images/college92.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "begusarai-medical-college",
  name: "Begusarai Medical College & Hospital",
  city: "Begusarai, Bihar",
  short: "Government medical college serving Begusarai district with MBBS education and hospital facilities.",
  img: "/images/college93.jpg",
  url: "#",
  type: "Government",
  hostel: true,
},
{
  id: "gdmc-dehradun",
  name: "Government Doon Medical College (GDMC)",
  city: "Dehradun, Uttarakhand",
  short:
    "Government medical college of Uttarakhand offering MBBS education with high patient load and strong clinical exposure.",
  img: "/images/college94.jpg",
  url: "#",
  type: "Government",
  nirf: "—",
  fees: "As per Govt norms",
  hostel: true,
  premium: true,
},
{
  id: "gmc-amritsar",
  name: "Government Medical College",
  city: "Amritsar, Punjab",
  short:
    "Established in 1943, one of the oldest government medical colleges in Punjab with very high patient load and strong clinical exposure.",
  img: "/images/college95.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
  premium: true,
},
{
  id: "gmc-patiala",
  name: "Government Medical College",
  city: "Patiala, Punjab",
  short:
    "Established in 1953, reputed state government medical college known for academics and large teaching hospital.",
  img: "/images/college96.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
  premium: true,
},
{
  id: "ggsmc-faridkot",
  name: "Guru Gobind Singh Medical College & Hospital",
  city: "Faridkot, Punjab",
  short:
    "Established in 1973, major government medical college with expanded MBBS seats and strong clinical departments.",
  img: "/images/college97.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "aims-mohali",
  name: "Dr. B.R. Ambedkar State Institute of Medical Sciences (AIMS)",
  city: "SAS Nagar (Mohali), Punjab",
  short:
    "Established in 2021, state government medical college providing modern MBBS education facilities.",
  img: "/images/college98.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "aiims-bathinda",
  name: "All India Institute of Medical Sciences (AIIMS)",
  city: "Bathinda, Punjab",
  short:
    "Established in 2019, central government AIIMS institute offering advanced medical education and healthcare services.",
  img: "/images/college99.jpg",
  url: "#",
  type: "Government",
  fees: "As per Central Govt norms",
  hostel: true,
  premium: true,
},
{
  id: "adesh-bathinda",
  name: "Adesh Institute of Medical Sciences & Research (AIMSR)",
  city: "Bathinda, Punjab",
  short:
    "Established in 2006, private medical college with attached teaching hospital and good clinical exposure.",
  img: "/images/college100.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "cmc-ludhiana",
  name: "Christian Medical College (CMC)",
  city: "Ludhiana, Punjab",
  short:
    "Established in 1894, reputed minority medical institution known for strong academics and ethical medical training.",
  img: "/images/college101.jpg",
  url: "#",
  type: "Private",
  hostel: true,
  premium: true,
},
{
  id: "dmch-ludhiana",
  name: "Dayanand Medical College & Hospital (DMCH)",
  city: "Ludhiana, Punjab",
  short:
    "Established in 1963, one of North India’s most reputed private medical colleges with very high patient load.",
  img: "/images/college102.jpg",
  url: "#",
  type: "Private",
  hostel: true,
  premium: true,
},
{
  id: "gian-sagar-banur",
  name: "Gian Sagar Medical College & Hospital",
  city: "Banur, Patiala, Punjab",
  short:
    "Established around 2020, modern private medical college with developing infrastructure.",
  img: "/images/college103.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "pims-jalandhar",
  name: "Punjab Institute of Medical Sciences (PIMS)",
  city: "Jalandhar, Punjab",
  short:
    "Established around 2011, well-known private medical college with large teaching hospital.",
  img: "/images/college104.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "sgrdimsr-amritsar",
  name: "Sri Guru Ram Das Institute of Medical Sciences & Research",
  city: "Amritsar, Punjab",
  short:
    "Established around 1997, reputed private medical college with strong Sikh minority background.",
  img: "/images/college105.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "rimt-gobindgarh",
  name: "RIMT Medical College & Hospital",
  city: "Gobindgarh, Punjab",
  short:
    "Established around 2024, new private medical college with limited initial MBBS intake.",
  img: "/images/college106.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "pgims-rohtak",
  name: "Pt. B.D. Sharma Post Graduate Institute of Medical Sciences",
  city: "Rohtak, Haryana",
  short:
    "Major state government medical institute with very high patient load, strong academics and extensive clinical exposure.",
  img: "/images/college107.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
  premium: true,
},
{
  id: "bps-women-sonepat",
  name: "BPS Government Medical College for Women",
  city: "Sonepat, Haryana",
  short:
    "State government medical college exclusively for women, known for disciplined academics and clinical training.",
  img: "/images/college108.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "esic-faridabad",
  name: "ESIC Medical College & Hospital",
  city: "Faridabad, Haryana",
  short:
    "Central government (ESIC) medical college with modern infrastructure and strong hospital services.",
  img: "/images/college109.jpg",
  url: "#",
  type: "Government",
  fees: "As per Central Govt norms",
  hostel: true,
},
{
  id: "kcgmc-karnal",
  name: "Kalpana Chawla Government Medical College",
  city: "Karnal, Haryana",
  short:
    "State government medical college providing quality MBBS education with developing super-speciality services.",
  img: "/images/college110.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "abvgmc-chhainsa",
  name: "Shri Atal Bihari Vajpayee Government Medical College",
  city: "Chhainsa, Faridabad, Haryana",
  short:
    "State government medical college aimed at strengthening healthcare services in the Faridabad region.",
  img: "/images/college111.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "shkmc-nalhar",
  name: "Shaheed Hasan Khan Mewati Government Medical College",
  city: "Nalhar (Mewat), Haryana",
  short:
    "State government medical college serving Mewat region with strong community health focus and clinical exposure.",
  img: "/images/college112.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "nrsmc-bhiwani",
  name: "Pt. Neki Ram Sharma Government Medical College",
  city: "Bhiwani, Haryana",
  short:
    "Newly established and approved state government medical college with modern facilities.",
  img: "/images/college113.jpg",
  url: "#",
  type: "Government",
  fees: "As per State Govt norms",
  hostel: true,
},
{
  id: "maharaja-agrasen-agroha",
  name: "Maharaja Agrasen Medical College",
  city: "Agroha, Hisar, Haryana",
  short:
    "Private medical college at Agroha known for its large hospital campus and growing clinical exposure.",
  img: "/images/college114.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "adesh-shahabad-kurukshetra",
  name: "Adesh Medical College & Hospital",
  city: "Shahabad, Kurukshetra, Haryana",
  short:
    "Private medical college with attached multi-specialty hospital offering MBBS education.",
  img: "/images/college115.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "nc-medical-panipat",
  name: "N.C. Medical College & Hospital",
  city: "Panipat, Haryana",
  short:
    "Private medical college providing MBBS education with modern infrastructure and hospital facilities.",
  img: "/images/college116.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "world-medical-jhajjar",
  name: "World College of Medical Sciences & Research",
  city: "Jhajjar, Haryana",
  short:
    "Established private medical college with developing academics and clinical exposure.",
  img: "/images/college117.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "al-falah-faridabad",
  name: "Al Falah School of Medical Sciences & Research Centre",
  city: "Dhauj, Faridabad, Haryana",
  short:
    "Minority university-based medical college offering MBBS education with modern facilities.",
  img: "/images/college118.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "sgt-gurugram",
  name: "Faculty of Medicine & Health Sciences (SGT University)",
  city: "Gurugram, Haryana",
  short:
    "Private university medical college with comprehensive teaching hospital and academic environment.",
  img: "/images/college119.jpg",
  url: "#",
  type: "Private",
  hostel: true,
},
{
  id: "bmcri-bengaluru-2",
  name: "Bangalore Medical College & Research Institute (BMCRI)",
  city: "Bengaluru, Karnataka",
  short: "Top government medical college with very high patient load and strong academics.",
  img: "/images/college138.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "ims-belagavi-2",
  name: "Belagavi Institute of Medical Sciences",
  city: "Belagavi, Karnataka",
  short: "Government medical college serving North Karnataka region.",
  img: "/images/college139.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "ims-bidar-2",
  name: "Bidar Institute of Medical Sciences",
  city: "Bidar, Karnataka",
  short: "State government medical college with developing infrastructure.",
  img: "/images/college140.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "ims-chamarajanagar-2",
  name: "Chamarajanagar Institute of Medical Sciences",
  city: "Chamarajanagar, Karnataka",
  short: "Government medical college focused on regional healthcare.",
  img: "/images/college141.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "ims-chikkaballapur-2",
  name: "Chikkaballapura Institute of Medical Sciences",
  city: "Chikkaballapur, Karnataka",
  short: "Government medical college with modern facilities.",
  img: "/images/college142.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "esic-bangalore-2",
  name: "ESIC Medical College",
  city: "Bengaluru, Karnataka",
  short: "Central government ESIC medical college with modern campus and hospital.",
  img: "/images/college143.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 – ₹1,25,000 / year",
  hostel: true,
},
{
  id: "gims-gadag-2",
  name: "Gadag Institute of Medical Sciences",
  city: "Gadag, Karnataka",
  short: "Government medical college offering MBBS education with clinical exposure.",
  img: "/images/college144.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "gims-kalaburagi-2",
  name: "Gulbarga Institute of Medical Sciences",
  city: "Kalaburagi (Gulbarga), Karnataka",
  short: "Government medical college serving Kalyana Karnataka region.",
  img: "/images/college145.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "hims-hassan-2",
  name: "Hassan Institute of Medical Sciences",
  city: "Hassan, Karnataka",
  short: "Well-known government medical college with good academic reputation.",
  img: "/images/college146.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "kims-hubballi-2",
  name: "Karnataka Institute of Medical Sciences (KIMS)",
  city: "Hubballi (Dharwad), Karnataka",
  short: "Highly reputed government medical college with strong clinical exposure.",
  img: "/images/college147.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "kims-koppal-2",
  name: "Koppal Institute of Medical Sciences",
  city: "Koppal, Karnataka",
  short: "Government medical college with developing hospital facilities.",
  img: "/images/college148.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "kims-madikeri-2",
  name: "Kodagu Institute of Medical Sciences",
  city: "Madikeri, Karnataka",
  short: "Government medical college serving Kodagu district.",
  img: "/images/college149.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "mims-mandya-2",
  name: "Mandya Institute of Medical Sciences",
  city: "Mandya, Karnataka",
  short: "Reputed government medical college with high patient inflow.",
  img: "/images/college150.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "mmcri-mysuru-2",
  name: "Mysore Medical College & Research Institute (MMCRI)",
  city: "Mysuru, Karnataka",
  short: "Historic government medical college with excellent academics and clinical exposure.",
  img: "/images/college151.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "rims-raichur-2",
  name: "Raichur Institute of Medical Sciences",
  city: "Raichur, Karnataka",
  short: "Government medical college serving North-Eastern Karnataka.",
  img: "/images/college152.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "sims-shivamogga-2",
  name: "Shimoga Institute of Medical Sciences",
  city: "Shivamogga, Karnataka",
  short: "State government medical college with strong teaching hospital.",
  img: "/images/college153.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "abvmc-bangalore-2",
  name: "Shri Atal Bihari Vajpayee Medical College & Research Institute",
  city: "Bengaluru, Karnataka",
  short: "Newer government medical college with modern facilities.",
  img: "/images/college154.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "vims-ballari-2",
  name: "Vijaynagar Institute of Medical Sciences",
  city: "Ballari (Bellary), Karnataka",
  short: "Well-established government medical college serving Kalyana Karnataka region.",
  img: "/images/college155.jpg",
  url: "#",
  type: "Government",
  fees: "₹65,000 – ₹75,000 / year",
  hostel: true,
},
{
  id: "ms-ramaiah-bangalore",
  name: "M.S. Ramaiah Medical College",
  city: "Bengaluru, Karnataka",
  short: "One of the most reputed private medical colleges in Karnataka with strong academics and clinical exposure.",
  img: "/images/college156.jpg",
  url: "#",
  type: "Private",
  fees: "₹10 – 11 Lakhs / year",
  hostel: true,
  premium: true,
},
{
  id: "pesimsr-bangalore",
  name: "PES Institute of Medical Sciences & Research",
  city: "Bengaluru, Karnataka",
  short: "Private medical college offering MBBS education with modern facilities and teaching hospital.",
  img: "/images/college157.jpg",
  url: "#",
  type: "Private",
  fees: "₹9 – 10 Lakhs / year",
  hostel: true,
},
{
  id: "bgs-bangalore",
  name: "BGS Medical College",
  city: "Bengaluru, Karnataka",
  short: "Private medical college known for affordable fee structure and clinical training.",
  img: "/images/college158.jpg",
  url: "#",
  type: "Private",
  fees: "₹9 – 10 Lakhs / year",
  hostel: true,
},
{
  id: "khaja-bande-nawaz-gulbarga",
  name: "Khaja Bande Nawaz Institute of Medical Sciences",
  city: "Kalaburagi (Gulbarga), Karnataka",
  short: "Minority medical college providing MBBS education with good clinical exposure.",
  img: "/images/college159.jpg",
  url: "#",
  type: "Private",
  fees: "₹8 – 9 Lakhs / year",
  hostel: true,
},
{
  id: "east-point-bangalore",
  name: "East Point College of Medical Sciences & Research Centre",
  city: "Bengaluru, Karnataka",
  short: "Private medical college with developing infrastructure and hospital facilities.",
  img: "/images/college160.jpg",
  url: "#",
  type: "Private",
  fees: "₹9 – 10 Lakhs / year",
  hostel: true,
},
{
  id: "dr-br-ambedkar-bangalore",
  name: "Dr. B.R. Ambedkar Medical College",
  city: "Bengaluru, Karnataka",
  short: "Well-known private medical college with long-standing reputation in Karnataka.",
  img: "/images/college161.jpg",
  url: "#",
  type: "Private",
  fees: "₹9 – 10 Lakhs / year",
  hostel: true,
},
{
  id: "shridevi-tumkur",
  name: "Shridevi Institute of Medical Sciences & Research Hospital",
  city: "Tumakuru (Tumkur), Karnataka",
  short: "Private medical college offering MBBS education with attached teaching hospital.",
  img: "/images/college162.jpg",
  url: "#",
  type: "Private",
  fees: "₹8 – 9 Lakhs / year",
  hostel: true,
},
{
  id: "navodaya-raichur",
  name: "Navodaya Medical College & Research Hospital",
  city: "Raichur, Karnataka",
  short: "Private medical college known for clinical exposure and affordable fee range.",
  img: "/images/college163.jpg",
  url: "#",
  type: "Private",
  fees: "₹8 – 9 Lakhs / year",
  hostel: true,
},
{
  id: "mvj-bangalore",
  name: "MVJ Medical College & Research Hospital",
  city: "Bengaluru, Karnataka",
  short: "Private medical college with modern infrastructure and teaching hospital.",
  img: "/images/college164.jpg",
  url: "#",
  type: "Private",
  fees: "₹9 – 10 Lakhs / year",
  hostel: true,
},
{
  id: "kmc-manipal",
  name: "Kasturba Medical College",
  city: "Manipal, Karnataka",
  short: "One of India’s most reputed deemed medical colleges with excellent academics and global exposure.",
  img: "/images/college165.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹18 – 19 Lakhs / year",
  hostel: true,
  premium: true,
},
{
  id: "kmc-mangalore",
  name: "Kasturba Medical College",
  city: "Mangalore, Karnataka",
  short: "Renowned deemed medical college known for strong clinical training and academics.",
  img: "/images/college166.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹18 – 19 Lakhs / year",
  hostel: true,
  premium: true,
},
{
  id: "jss-mysore",
  name: "JSS Medical College",
  city: "Mysuru, Karnataka",
  short: "Well-known deemed medical college with modern hospital facilities and good patient flow.",
  img: "/images/college167.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹16 – 17 Lakhs / year",
  hostel: true,
},
{
  id: "jnmc-kle-belagavi",
  name: "Jawaharlal Nehru Medical College (KLE)",
  city: "Belagavi, Karnataka",
  short: "Established deemed medical college under KLE University with strong academic reputation.",
  img: "/images/college168.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹16 – 17 Lakhs / year",
  hostel: true,
},
{
  id: "ks-hegde-mangalore",
  name: "K.S. Hegde Medical Academy (NITTE)",
  city: "Mangalore, Karnataka",
  short: "Deemed medical college under NITTE University with modern infrastructure and academics.",
  img: "/images/college169.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹16 – 17 Lakhs / year",
  hostel: true,
},
{
  id: "sd-urs-kolar",
  name: "Sri Devaraj Urs Medical College",
  city: "Kolar, Karnataka",
  short: "Deemed medical college offering MBBS education with well-established hospital facilities.",
  img: "/images/college170.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹15 – 16 Lakhs / year",
  hostel: true,
},
{
  id: "blde-bijapur",
  name: "Shri B.M. Patil Medical College",
  city: "Bijapur (Vijayapura), Karnataka",
  short: "Deemed medical college under BLDE University with strong clinical exposure.",
  img: "/images/college171.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹15 – 16 Lakhs / year",
  hostel: true,
},
{
  id: "yenepoya-mangalore",
  name: "Yenepoya Medical College",
  city: "Mangalore, Karnataka",
  short: "Deemed medical college with good academics and multi-specialty hospital exposure.",
  img: "/images/college172.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹16 – 17 Lakhs / year",
  hostel: true,
},
{
  id: "sri-siddhartha-tumkur",
  name: "Sri Siddhartha Medical College",
  city: "Tumakuru (Tumkur), Karnataka",
  short: "Private medical college with long-standing reputation and good academic environment.",
  img: "/images/college173.jpg",
  url: "#",
  type: "Private",
  fees: "₹14 – 15 Lakhs / year",
  hostel: true,
},

{
  id: "gmc-bhopal",
  name: "Gandhi Medical College",
  city: "Bhopal, Madhya Pradesh",
  short: "One of the oldest and most reputed government medical colleges in MP with very high patient load.",
  img: "/images/college174.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "nsbmc-jabalpur",
  name: "Netaji Subhash Chandra Bose Medical College",
  city: "Jabalpur, Madhya Pradesh",
  short: "Reputed government medical college serving Mahakoshal region with strong clinical exposure.",
  img: "/images/college175.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
},
{
  id: "mgm-indore",
  name: "MGM Medical College",
  city: "Indore, Madhya Pradesh",
  short: "Top government medical college of MP known for academics and major referral hospitals.",
  img: "/images/college176.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "grmc-gwalior",
  name: "Gajra Raja Medical College",
  city: "Gwalior, Madhya Pradesh",
  short: "Well-established government medical college with strong academic heritage.",
  img: "/images/college177.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
},
{
  id: "ssmc-rewa",
  name: "Shyam Shah Medical College",
  city: "Rewa, Madhya Pradesh",
  short: "Government medical college serving Vindhya region with good clinical exposure.",
  img: "/images/college178.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
},
{
  id: "bmc-sagar",
  name: "Bundelkhand Medical College",
  city: "Sagar, Madhya Pradesh",
  short: "Government medical college established to strengthen healthcare in Bundelkhand region.",
  img: "/images/college179.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
},
{
  id: "rd-gardi-ujjain-govt",
  name: "RD Gardi Medical College (Government Seats)",
  city: "Ujjain, Madhya Pradesh",
  short: "Private medical college with government quota seats under MP state counselling.",
  img: "/images/college180.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
},
{
  id: "abvgmc-vidisha",
  name: "Atal Bihari Vajpayee Government Medical College",
  city: "Vidisha, Madhya Pradesh",
  short: "State government medical college providing affordable MBBS education.",
  img: "/images/college181.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,00,000 / year",
  hostel: true,
},
{
  id: "pcms-bhopal",
  name: "Peoples College of Medical Sciences & Research Centre",
  city: "Bhopal, Madhya Pradesh",
  short: "Private medical college in Bhopal with attached teaching hospital and good clinical exposure.",
  img: "/images/college182.jpg",
  url: "#",
  type: "Private",
  fees: "₹12 – 14 Lakhs / year",
  hostel: true,
},
{
  id: "lnmc-bhopal",
  name: "LN Medical College",
  city: "Bhopal, Madhya Pradesh",
  short: "Private medical college known for modern infrastructure and academics.",
  img: "/images/college183.jpg",
  url: "#",
  type: "Private",
  fees: "₹14 – 16 Lakhs / year",
  hostel: true,
},
{
  id: "rkdf-bhopal",
  name: "RKDF Medical College Hospital & Research Centre",
  city: "Bhopal, Madhya Pradesh",
  short: "Private medical college offering MBBS education with attached hospital facilities.",
  img: "/images/college184.jpg",
  url: "#",
  type: "Private",
  fees: "₹11 – 13 Lakhs / year",
  hostel: true,
},
{
  id: "index-indore",
  name: "Index Medical College Hospital & Research Centre",
  city: "Indore, Madhya Pradesh",
  short: "Private medical college with large campus and multi-specialty hospital in Indore.",
  img: "/images/college185.jpg",
  url: "#",
  type: "Private",
  fees: "₹14 – 16 Lakhs / year",
  hostel: true,
},
{
  id: "amaltas-dewas",
  name: "Amaltas Institute of Medical Sciences",
  city: "Dewas, Madhya Pradesh",
  short: "Private medical college providing MBBS education with developing hospital infrastructure.",
  img: "/images/college186.jpg",
  url: "#",
  type: "Private",
  fees: "₹12 – 14 Lakhs / year",
  hostel: true,
},
{
  id: "mahaveer-bhopal",
  name: "Mahaveer Institute of Medical Sciences",
  city: "Bhopal, Madhya Pradesh",
  short: "Private medical college offering affordable MBBS education in Bhopal.",
  img: "/images/college187.jpg",
  url: "#",
  type: "Private",
  fees: "₹11 – 13 Lakhs / year",
  hostel: true,
},
{
  id: "lnct-indore",
  name: "LNCT Medical College",
  city: "Indore, Madhya Pradesh",
  short: "Private medical college under LNCT group with good academic environment.",
  img: "/images/college188.jpg",
  url: "#",
  type: "Private",
  fees: "₹13 – 15 Lakhs / year",
  hostel: true,
},
{
  id: "rd-gardi-ujjain-deemed",
  name: "RD Gardi Medical College (Deemed Seats)",
  city: "Ujjain, Madhya Pradesh",
  short:
    "Deemed university seats at RD Gardi Medical College offering MBBS education with established hospital facilities.",
  img: "/images/college189.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹18 – 20 Lakhs / year",
  hostel: true,
},
{
  id: "grant-jj-mumbai",
  name: "Grant Medical College & Sir J.J. Hospital",
  city: "Mumbai, Maharashtra",
  short: "One of India’s oldest government medical colleges with very high patient load.",
  img: "/images/college190.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
  premium: true,
},
{
  id: "kem-mumbai",
  name: "Seth G.S. Medical College (KEM Hospital)",
  city: "Mumbai, Maharashtra",
  short: "Top-tier government medical college with excellent academics and clinical exposure.",
  img: "/images/college191.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
  premium: true,
},
{
  id: "ltmmc-sion",
  name: "Lokmanya Tilak Municipal Medical College (Sion)",
  city: "Mumbai, Maharashtra",
  short: "Renowned municipal medical college with one of the busiest hospitals in Mumbai.",
  img: "/images/college192.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "tnmc-nair",
  name: "Topiwala National Medical College (Nair Hospital)",
  city: "Mumbai, Maharashtra",
  short: "Prestigious government medical college associated with Nair Hospital.",
  img: "/images/college193.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "bjmc-pune",
  name: "B.J. Government Medical College",
  city: "Pune, Maharashtra",
  short: "Highly reputed government medical college in Maharashtra with strong academics.",
  img: "/images/college194.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
  premium: true,
},
{
  id: "gmc-nagpur",
  name: "Government Medical College",
  city: "Nagpur, Maharashtra",
  short: "Major government medical college serving Vidarbha region.",
  img: "/images/college195.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "gmc-aurangabad",
  name: "Government Medical College",
  city: "Aurangabad, Maharashtra",
  short: "Government medical college with large teaching hospital in Marathwada region.",
  img: "/images/college196.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "gmc-miraj",
  name: "Government Medical College",
  city: "Miraj, Maharashtra",
  short: "Reputed government medical college with strong clinical exposure.",
  img: "/images/college197.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "igmc-nagpur",
  name: "Indira Gandhi Government Medical College",
  city: "Nagpur, Maharashtra",
  short: "Well-known government medical college with extensive hospital services.",
  img: "/images/college198.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "rgmc-thane",
  name: "Rajiv Gandhi Medical College",
  city: "Thane, Maharashtra",
  short: "Municipal government medical college serving Thane and Mumbai suburban region.",
  img: "/images/college199.jpg",
  url: "#",
  type: "Government",
  fees: "₹1.1 – 1.3 Lakh / year",
  hostel: true,
},
{
  id: "dy-patil-pune",
  name: "DY Patil Medical College",
  city: "Pune, Maharashtra",
  short: "Reputed deemed medical college with modern infrastructure and strong clinical exposure.",
  img: "/images/college200.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹22 – 25 Lakhs / year",
  hostel: true,
  premium: true,
},
{
  id: "bharati-vidyapeeth-pune",
  name: "Bharati Vidyapeeth Medical College",
  city: "Pune, Maharashtra",
  short: "Well-known deemed medical college under Bharati Vidyapeeth with large teaching hospital.",
  img: "/images/college201.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹20 – 23 Lakhs / year",
  hostel: true,
},
{
  id: "mgm-navi-mumbai",
  name: "MGM Medical College",
  city: "Navi Mumbai, Maharashtra",
  short: "Deemed medical college offering MBBS education with good academics and hospital exposure.",
  img: "/images/college202.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹18 – 22 Lakhs / year",
  hostel: true,
},
{
  id: "kims-karad",
  name: "Krishna Institute of Medical Sciences",
  city: "Karad, Maharashtra",
  short: "Deemed medical college with strong academic background and multi-specialty hospital.",
  img: "/images/college203.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹20 – 22 Lakhs / year",
  hostel: true,
},
{
  id: "vasantrao-pawar-nashik",
  name: "Dr. Vasantrao Pawar Medical College",
  city: "Nashik, Maharashtra",
  short: "Private medical college providing MBBS education with attached teaching hospital.",
  img: "/images/college204.jpg",
  url: "#",
  type: "Private",
  fees: "₹15 – 18 Lakhs / year",
  hostel: true,
},
{
  id: "jnmc-wardha",
  name: "Jawaharlal Nehru Medical College",
  city: "Wardha, Maharashtra",
  short: "Deemed medical college under Datta Meghe group with strong academics and clinical training.",
  img: "/images/college205.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹14 – 17 Lakhs / year",
  hostel: true,
},
{
  id: "acp-dhule",
  name: "ACP Medical College",
  city: "Dhule, Maharashtra",
  short: "Private medical college with developing infrastructure and hospital facilities.",
  img: "/images/college206.jpg",
  url: "#",
  type: "Private",
  fees: "₹13 – 16 Lakhs / year",
  hostel: true,
},
{
  id: "nkp-salve-nagpur",
  name: "NKP Salve Institute of Medical Sciences",
  city: "Nagpur, Maharashtra",
  short: "Private medical college with good academic reputation and clinical exposure.",
  img: "/images/college207.jpg",
  url: "#",
  type: "Private",
  fees: "₹18 – 20 Lakhs / year",
  hostel: true,
},
{
  id: "terna-navi-mumbai",
  name: "Terna Medical College",
  city: "Navi Mumbai, Maharashtra",
  short: "Private medical college known for affordable fee range and clinical exposure.",
  img: "/images/college208.jpg",
  url: "#",
  type: "Private",
  fees: "₹16 – 18 Lakhs / year",
  hostel: true,
},
{
  id: "ulhas-patil-jalgaon",
  name: "Dr. Ulhas Patil Medical College",
  city: "Jalgaon, Maharashtra",
  short: "Private medical college providing MBBS education with modern facilities.",
  img: "/images/college209.jpg",
  url: "#",
  type: "Private",
  fees: "₹12 – 15 Lakhs / year",
  hostel: true,
},
{
  id: "dy-patil-kolhapur",
  name: "DY Patil Medical College",
  city: "Kolhapur, Maharashtra",
  short: "Deemed medical college under DY Patil group with modern infrastructure and teaching hospital.",
  img: "/images/college220.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹25 – 28 Lakhs / year",
  hostel: true,
  premium: true,
},
{
  id: "datta-meghe-wardha",
  name: "Datta Meghe Medical College",
  city: "Wardha, Maharashtra",
  short: "Deemed medical college under Datta Meghe group with strong academics and clinical exposure.",
  img: "/images/college221.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹22 – 25 Lakhs / year",
  hostel: true,
},
{
  id: "mgm-aurangabad-deemed",
  name: "MGM Medical College",
  city: "Aurangabad, Maharashtra",
  short: "Deemed medical college offering MBBS education with large hospital facilities.",
  img: "/images/college222.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹22 – 25 Lakhs / year",
  hostel: true,
},
{
  id: "symbiosis-women-pune",
  name: "Symbiosis Medical College for Women",
  city: "Pune, Maharashtra",
  short: "Private medical college exclusively for women with modern campus and academic environment.",
  img: "/images/college223.jpg",
  url: "#",
  type: "Private",
  fees: "₹10 – 12 Lakhs / year",
  hostel: true,
},
{
  id: "kims-karad-deemed-2",
  name: "Krishna Institute of Medical Sciences",
  city: "Karad, Maharashtra",
  short: "Deemed medical college with well-established multi-specialty hospital and academics.",
  img: "/images/college224.jpg",
  url: "#",
  type: "Deemed",
  fees: "₹22 – 25 Lakhs / year",
  hostel: true,
},
{
  id: "aiims-delhi",
  name: "All India Institute of Medical Sciences (AIIMS Delhi)",
  city: "New Delhi",
  short: "India’s top central government medical institute with world-class academics and very high patient load.",
  img: "/images/college225.jpg",
  url: "#",
  type: "Government",
  fees: "₹1,600 / year",
  hostel: true,
  premium: true,
},
{
  id: "mamc-delhi",
  name: "Maulana Azad Medical College (MAMC)",
  city: "New Delhi",
  short: "Premier state government medical college affiliated with LNJP Hospital.",
  img: "/images/college226.jpg",
  url: "#",
  type: "Government",
  fees: "₹15,000 / year",
  hostel: true,
  premium: true,
},
{
  id: "lhmc-delhi",
  name: "Lady Hardinge Medical College (LHMC)",
  city: "New Delhi",
  short: "Renowned government medical college primarily for women with excellent clinical exposure.",
  img: "/images/college227.jpg",
  url: "#",
  type: "Government",
  fees: "₹12,000 / year",
  hostel: true,
},
{
  id: "ucms-delhi",
  name: "University College of Medical Sciences (UCMS)",
  city: "Delhi",
  short: "State government medical college affiliated with Guru Teg Bahadur Hospital.",
  img: "/images/college228.jpg",
  url: "#",
  type: "Government",
  fees: "₹15,000 / year",
  hostel: true,
},
{
  id: "bsamc-rohini",
  name: "Dr. Baba Saheb Ambedkar Medical College (BSAMC)",
  city: "Rohini, Delhi",
  short: "State government medical college serving North Delhi region.",
  img: "/images/college229.jpg",
  url: "#",
  type: "Government",
  fees: "₹15,000 / year",
  hostel: true,
},
{
  id: "abvims-rml-delhi",
  name: "Atal Bihari Vajpayee Institute of Medical Sciences (ABVIMS, RML)",
  city: "New Delhi",
  short: "Central government medical institute attached to Ram Manohar Lohia Hospital.",
  img: "/images/college230.jpg",
  url: "#",
  type: "Government",
  fees: "₹1 – 2 Lakh / year",
  hostel: true,
},
{
  id: "vmmc-delhi",
  name: "Vardhman Mahavir Medical College (VMMC)",
  city: "New Delhi",
  short: "Central government medical college attached to Safdarjung Hospital.",
  img: "/images/college231.jpg",
  url: "#",
  type: "Government",
  fees: "₹40,000 – 50,000 / year",
  hostel: true,
},


 
];

export default function CollegesPage() {
  const [query, setQuery] = useState("");
  const [stateFilter, setStateFilter] = useState("");
  const [onlyPremium, setOnlyPremium] = useState(false);

  const states = useMemo(() => {
    const s = new Set<string>();
    colleges.forEach((c) => {
      if (c.city) {
        const parts = c.city.split(",");
        if (parts.length > 1) s.add(parts[parts.length - 1].trim());
        else s.add(c.city.trim());
      }
    });
    return Array.from(s).filter(Boolean).sort();
  }, []);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return colleges.filter((c) => {
      if (onlyPremium && !c.premium) return false;
      if (stateFilter) {
        if (!c.city || !c.city.toLowerCase().includes(stateFilter.toLowerCase())) return false;
      }
      if (!q) return true;
      return (
        c.name.toLowerCase().includes(q) ||
        (c.city && c.city.toLowerCase().includes(q)) ||
        (c.short && c.short.toLowerCase().includes(q))
      );
    });
  }, [query, stateFilter, onlyPremium]);

  return (
    <main className="page">
      <div className="container">
        <header className="header">
          <h1>Top Medical Colleges You Can Get Through Our Guidance</h1>
          <p className="lead">Personalised college shortlisting based on your rank, budget & category.</p>
        </header>

        <div className="controls">
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search college, city or keyword..."
            className="input"
            aria-label="Search colleges"
          />
          <select
            value={stateFilter}
            onChange={(e) => setStateFilter(e.target.value)}
            className="select"
            aria-label="Filter by state"
          >
            <option value="">All States</option>
            {states.map((s) => (
              <option key={s} value={s}>
                {s}
              </option>
            ))}
          </select>

          <label className="checkboxLabel">
            <input
              type="checkbox"
              checked={onlyPremium}
              onChange={(e) => setOnlyPremium(e.target.checked)}
            />
            Premium only
          </label>

          <div className="count">Showing {filtered.length} colleges</div>
        </div>

        <section className="grid">
          {filtered.map((c) => (
            <article key={c.id} className={`card ${c.premium ? "card-premium" : ""}`}>
              {c.premium && <div className="badge">Premium</div>}
              <div className="imgWrap">
                <Image src={c.img} alt={c.name} fill style={{ objectFit: "cover" }} />
              </div>

              <div className="cardBody">
                <div className="titleRow">
                  <div>
                    <h3 className="cardTitle">{c.name}</h3>
                    <div className="city">{c.city}</div>
                  </div>

                  <div className={`typePill ${c.type?.toLowerCase() || "private"}`}>{c.type ?? "Private"}</div>
                </div>

                <p className="desc">{c.short}</p>

                <div className="highlights">
                  <div className="chip"><strong>NIRF</strong><span>{c.nirf ?? "—"}</span></div>
                  <div className="chip"><strong>Fees</strong><span>{c.fees ?? "—"}</span></div>
                  <div className="chip"><strong>Closing Rank</strong><span>{c.closingRank ?? "—"}</span></div>
                  <div className="chip"><strong>Hostel</strong><span>{c.hostel ? "Available" : "Not Available"}</span></div>
                </div>

                <div className="ctaRow">
                  <Link href={c.url ?? "#"} legacyBehavior><a className="linkBtn">View Details →</a></Link>
                  <Link href={c.url ?? "#"} legacyBehavior><a className="primaryBtn">Check Eligibility →</a></Link>
                </div>
              </div>
            </article>
          ))}
        </section>
      </div>

      <style jsx>{`
        .page { background: #fff; color: #0f1724; min-height: 100vh; padding: 40px 12px; }
        .container { max-width: 1080px; margin: 0 auto; }

        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 24px; margin: 0; font-weight: 800; }
        .lead { margin-top: 8px; color: #64748b; }

        .controls {
          display: flex;
          flex-wrap: wrap;
          gap: 10px;
          align-items: center;
          justify-content: space-between;
          margin: 18px 0;
        }
        .input { padding: 8px 10px; border: 1px solid #d1d5db; border-radius: 6px; min-width: 180px; flex: 1; max-width: 420px; }
        .select { padding: 8px 10px; border-radius: 6px; border: 1px solid #d1d5db; }
        .checkboxLabel { display: inline-flex; align-items: center; gap: 6px; font-size: 14px; color: #334155; }
        .count { color: #64748b; font-size: 14px; }

        /* GRID: 1 column mobile, 2 columns >=768px */
        .grid {
          display: grid;
          grid-template-columns: 1fr;
          gap: 18px;
        }
        @media (min-width: 768px) {
          .grid { grid-template-columns: 1fr 1fr; }
        }

        .card {
          display: flex;
          flex-direction: column;
          background: #fff;
          border: 1px solid #e6e9ee;
          border-radius: 10px;
          overflow: hidden;
          box-shadow: 0 1px 3px rgba(15,23,36,0.04);
          transition: transform .18s ease, box-shadow .18s ease;
          position: relative;
          min-height: 300px;
        }
        .card:hover { transform: translateY(-6px) scale(1.01); box-shadow: 0 6px 24px rgba(2,6,23,0.08); }

        .card-premium { border-color: #f7d97f; box-shadow: 0 8px 30px rgba(247,217,127,0.08); }

        .badge {
          position: absolute; right: 12px; top: 12px;
          background: #fff8e6; color: #9a6b00; padding: 6px 10px; font-weight: 700; border-radius: 999px;
          border: 1px solid rgba(250,214,138,0.8); font-size: 12px;
        }

        .imgWrap { position: relative; height: 160px; background: #f3f4f6; }
        @media (min-width: 1024px) { .imgWrap { height: 180px; } }

        .cardBody { padding: 14px; display: flex; flex-direction: column; gap: 10px; flex: 1; }

        .titleRow { display:flex; align-items:flex-start; gap: 12px; }
        .cardTitle { margin: 0; font-size: 16px; }
        .city { font-size: 12px; color: #64748b; margin-top: 4px; }

        .typePill { font-size: 12px; padding: 6px 8px; border-radius: 8px; border: 1px solid #e6e9ee; background: #f8fafc; color: #0f1724; white-space: nowrap; }
        .typePill.government { background: #ecfdf5; color: #065f46; border-color: #d1fae5; }
        .typePill.deemed { background: #eef2ff; color: #3730a3; border-color: #e0e7ff; }

        .desc { color: #0f1724; margin: 0; font-size: 13px; line-height: 1.3; max-height: 3.9em; overflow: hidden; }

        .highlights { display:flex; flex-wrap:wrap; gap:8px; align-items:center; }
        .chip { display:flex; gap:8px; align-items:center; padding:6px 8px; border-radius:8px; background:#fbfdff; border:1px solid #f1f5f9; font-size:12px; color:#0f1724; }
        .chip strong { margin-right:4px; font-weight:700; font-size:12px; }

        .ctaRow { display:flex; gap:10px; align-items:center; margin-top:6px; }
        .linkBtn { padding:7px 12px; border-radius:8px; border:1px solid #cbd5e1; text-decoration:none; color:#0366d6; font-size:13px; background: #fff; }
        .primaryBtn { margin-left:auto; padding:8px 12px; border-radius:8px; background:#0366d6; color:#fff; text-decoration:none; font-weight:600; font-size:13px; }

      `}</style>
    </main>
  );
}